[package]
cargo-toml-patch-comments = [
    "remove feature for building / statically linking vendored OpenSSL sources",
    "relax parking_lot_core dependency from =0.9.10 to ^0.9.10",
    "update ron (to 0.9): https://github.com/gitui-org/gitui/commit/5755c096b42553de98490cf788dff1a4925bc574",
    "allow unicode-truncate 1.0",
    """
    bump struct-patch to 0.9
    https://github.com/gitui-org/gitui/pull/2583
    """,
]
license-files.exclude = [
    "wix/License.rtf",
]

[requires]
# build script fails hard if git is not available
# with git available, the commit hash embedded in the binary is ""
build = [
    "/usr/bin/git",
]

[scripts]
# embedded version string is "nightly" if GITUI_RELEASE is not set
build.pre = [
    "export GITUI_RELEASE=1",
]
install.pre = [
    "export GITUI_RELEASE=1",
]
check.pre = [
    "export GITUI_RELEASE=1",
]

